apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-config
spec:
  tls:
    - hosts:
        - posd-app.com
      secretName: my-tls
  rules:
    - host: posd-app.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 443
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: webserver-service
                port:
                  number: 5000
