apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
data:
  FLASK_APP: "app/__init__.py"
  PROJECT_NAME: "webserver"
  KEYCLOAK_URL: "https://posd-app-keycloak.com/realms/Istio/protocol/openid-connect/token"
