apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: webserver-auth
spec:
  selector:
    matchLabels:
      app: webserver
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: ["GET"]
            paths:
              [
                "/",
                "/static/tailwind/tailwind.css",
                "/books",
                "/dashboard",
                "/login",
              ]
        - operation:
            methods: ["POST"]
            paths: ["/login", "/logout"]
