apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: webserver
          image: andrei8080/webserver:dev-stefan
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: webserver-config
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: webserver
  type: ClusterIP
