apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: webserver-request-authentication
spec:
  selector:
    matchLabels:
      app: webserver
  jwtRules:
    - issuer: "https://posd-app-keycloak.com/realms/Istio"
      jwksUri: "http://10.96.51.185:88/realms/Istio/protocol/openid-connect/certs"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: webserver-auth
spec:
  selector:
    matchLabels:
      app: webserver
  action: ALLOW
  rules:
    # General access rule without restrictions
    - to:
        - operation:
            methods: ["GET"]
            paths:
              [
                "/",
                "/static/tailwind/tailwind.css",
                "/books",
                "/books/*",
                "/dashboard",
                "/login",
                "/requests",
                "/requests/*",
                "/teapot",
                "settings/*",
                "/api/permissions/*", 
                "/policy/editor/*"
              ]
        - operation:
            methods: ["POST"]
            paths: 
              [
                "/books", 
                "/books/reviews/*", 
                "/login", 
                "/logout",
                "/api/permissions/*", 
                "/policy/editor/*",
                "/policy/editor"
              ]
        - operation:
            methods: ["DELETE"]
            paths: ["/books/*"]

    # # Admin access rule
    - to:
        - operation:
            methods: ["GET"]
            paths: ["/policy/editor", "/api/permissions"]
        - operation:
            methods: ["POST"]
            paths: ["/api/permissions/*", "/policy/editor"]
      when:
        - key: request.auth.claims[resource_access][Istio][roles]
          values: ["admin"]