apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: webserver-request-authentication
spec:
  selector:
    matchLabels:
      app: webserver
  jwtRules:
    - issuer: "https://posd-app-keycloak.com/realms/Istio"
      jwksUri: "http://10.100.249.244:88/realms/Istio/protocol/openid-connect/certs"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: webserver-auth
spec:
  selector:
    matchLabels:
      app: webserver
  action: ALLOW
  rules:
    - to:
        - operation:
            methods: [ "GET" ]
            paths:
              [
                "/",
                "/static/tailwind/tailwind.css",
                "/books",
                "/books/*",
                "/dashboard",
                "/login",
                "/requests",
                "/requests/*",
                "/settings",
              ]
    - to:
        - operation:
            methods: [ "POST" ]
            paths: [ "/books", "/books/reviews/*", "/login", "/logout", "/settings/change_role" ]
    - to:
        - operation:
            methods: [ "DELETE" ]
            paths: [ "/books/*", "/settings/delete_role" ]
