apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-config
data:
  FLASK_APP: "app/__init__.py"
  PROJECT_NAME: "webserver"
  KEYCLOAK_IP: "http://10.103.125.136:8080/realms/Istio/protocol/openid-connect/token"
