apiVersion: v1
kind: ServiceAccount
metadata:
  name: webserver-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webserver-sa-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: webserver-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: webserver-sa
      containers:
        - name: webserver
          image: andradragne/webserver:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: webserver-config
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: http
  selector:
    app: webserver
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-policy-manager
rules:
- apiGroups: ["security.istio.io"]
  resources: ["authorizationpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webserver-policy-manager
subjects:
- kind: ServiceAccount
  name: webserver-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: istio-policy-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: verified-sa
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-sa
  namespace: default