apiVersion: v1
kind: ServiceAccount
metadata:
  name: webserver-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webserver-sa-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: webserver-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: webserver-sa
      containers:
        - name: webserver
          image: andradragne/webserver:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: webserver-config
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  ports:
    - port: 80
      targetPort: 5000
      name: http
  selector:
    app: webserver
  type: ClusterIP