apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: webserver-auth
  namespace: default
spec:
  selector:
    matchLabels:
      app: webserver
  jwtRules:
  - issuer: "https://posd-app-keycloak.com/realms/Istio"
    jwksUri: "http://10.110.162.21:88/realms/Istio/protocol/openid-connect/certs"
    forwardOriginalToken: true
    fromHeaders:
    - name: Authorization
      prefix: "Bearer "
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: webserver-auth
  namespace: default
spec:
  selector:
    matchLabels:
      app: webserver
  action: ALLOW
  rules:
  # Public routes
  - to:
    - operation:
        methods: ["GET", "POST"]
        paths: ["/", "/static/*", "/login", "/logout", "/dashboard", "/debug/*"]

  # Admin routes
  - to:
    - operation:
        methods: ["GET", "POST"]
        paths: ["/policy/editor", "/requests", "/api/permissions/*", "/books", "/books/*"]
    when:
    - key: request.auth.claims.resource_access.Istio.roles
      values: ["admin"]