apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: webserver-auth
spec:
  selector:
    matchLabels:
      app: webserver
  rules:
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            paths: ["/app"] # Allow unauthenticated access to `/app`
    - from:
        - source:
            requestPrincipals: ["*"]
      to:
        - operation:
            notPaths: ["/app"] # Require authentication for all other paths
